name: Release Valist

on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  draft-releases:
    runs-on: ubuntu-latest
    steps:
      - name: echo ref name.
        run: echo "tag name ${{ github.ref_name }}"
      - name: Checkout repository.
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.pat }}
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '>=20.5.1'
          cache: 'yarn'
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install modules.
        run: yarn setup
      - name: Install @hyperplay/cli globally
        run: npm install -g @hyperplay/cli
      - name: Download all artifacts, create hyperplay.yml, and upload to Valist
        run: export RELEASE_VERSION=${{ github.ref_name }} && export VALIST_PUBLISH_KEY=${{ secrets.VALIST_PUBLISH_KEY }} && yarn release:valist
